-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "workingDaysPerMonth" INTEGER NOT NULL DEFAULT 22;

-- AlterTable
ALTER TABLE "LeaveBalance" ALTER COLUMN "paidUsed" SET DEFAULT 0,
ALTER COLUMN "paidUsed" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sickUsed" SET DEFAULT 0,
ALTER COLUMN "sickUsed" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "unpaidUsed" SET DEFAULT 0,
ALTER COLUMN "unpaidUsed" SET DATA TYPE DOUBLE PRECISION;
